services:
    - postgresql
    - sqlite

sudo: false

language: perl6

perl6:
    - '2017.07'
    #- latest

#before_install:
#    - sudo apt-get -qq update
#    - sudo apt-get install -y sqlite3

before_script:
    # note the default postgres user has a blank password
    - psql -c 'create database sql92;' -U postgres
    - psql -U postgres -c 'create extension postgis;'

install:
    - rakudobrew build-zef
    # the following command avoids double-testing of the target module:
    - zef --deps-only install .
