# note this file should provide much of the services and before_install as DBIsh
services:
    - postgresql
    - mysql

sudo: false

language: perl6

perl6:
    - latest

#before_install:
#    - sudo apt-get -qq update
#    - sudo apt-get install -y sqlite3

before_script:
    # note the default postgres user has a blank password
    # from DBIish
    # mysql
    - mysql -e "CREATE DATABASE dbdishtest;" -uroot
    - mysql -e "CREATE USER 'testuser'@'localhost' IDENTIFIED BY 'testpass';" -uroot
    - mysql -e "GRANT ALL PRIVILEGES ON dbdishtest.* TO 'testuser'@'localhost';" -uroot
    # Pg
    - psql -c 'CREATE DATABASE dbdishtest;' -U postgres
    # for my testing
    - psql -c 'create user sql92 ;' -U postgres
    - psql -c 'create database sql92;' -U postgres
    # for later: need to install package postgis
    #- psql -U postgres -c 'create extension postgis;'

install:
    - rakudobrew build-zef
    # the following command avoids double-testing of the target module:
    - zef --deps-only install .
